---
# Copyright (C) 2018-2021 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018-2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage ESET Remote Administrator Server
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts: [ 'debops_contrib_eset_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::mariadb' ]
      keyring__dependent_apt_keys:
        - '{{ mariadb__keyring__dependent_apt_keys }}'

    - role: python
      tags: [ 'role::python', 'skip::python', 'role::mariadb' ]
      python__dependent_packages3:
        - '{{ mariadb__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ mariadb__python__dependent_packages2 }}'

    - role: etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ eset_server__etc_services__dependent_list }}'

    - role: ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ eset_server__ferm__dependent_rules }}'

    - role: mariadb
      tags: [ 'role::mariadb' ]
      mariadb__dependent_users:
        - '{{ eset_server__mariadb__dependent_users }}'

    - role: eset_server
      tags: [ 'role::eset_server' ]
